# Generated by Django 4.0.2 on 2022-03-13 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuser', '0003_dailypost_viptest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypost',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='viptest',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
