# Generated by Django 4.0.2 on 2022-03-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuser', '0004_alter_dailypost_date_alter_viptest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypost',
            name='body',
            field=models.TextField(max_length=10000000000000000000000000),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=10000000000000000000000000),
        ),
        migrations.AlterField(
            model_name='viptest',
            name='body',
            field=models.TextField(max_length=10000000000000000000000000),
        ),
    ]
