# Generated by Django 4.0.2 on 2022-03-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuser', '0005_alter_dailypost_body_alter_post_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypost',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='viptest',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
